urls:
  latest-snapshot: https://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
  nightly-build-plans: https://mirrors.tuna.tsinghua.edu.cn/stackage/stackage-nightly/
  lts-build-plans: https://mirrors.tuna.tsinghua.edu.cn/stackage/lts-haskell/
system-ghc: true
setup-info: https://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml

package-indices:
  - name: Tsinghua
    download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/package/
    http: http://mirrors.tuna.tsinghua.edu.cn/hackage/00-index.tar.gz

nix:
  enable: true
  pure: true
  packages: [glpk, pcre, zlib]
